version: '3.8'

services:
  phaser-game:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: nginx:alpine
    container_name: phaser-game
    ports:
      - "8080:80"
    restart: unless-stopped
